commit-message-incrementing: Disabled
continuous-delivery-fallback-tag: ''
mode: ContinuousDelivery
branches:
  master:
    regex: master
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    tracks-release-branches: false
    track-merge-target: false
    is-release-branch: false
    is-source-branch-for: ['hotfix','release']
    source-branches: ['hotfix','release']
  hotfix:
    regex: hotfix(es)?[/-]
    tag: 'hotfix.{BranchName}'
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    is-release-branch: false
    source-branches: ['master']
    is-source-branch-for: ['bug','feature','master']
  release:
    regex: releases?[/-]
    tag: useBranchName
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    is-release-branch: true
    tracks-release-branches: false
    is-source-branch-for: ['feature','bug']
    source-branches: ['release','master','feature','bug']
  feature:
    regex: features?[/-]
    tag: 'feature.{BranchName}'
    increment: None
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    is-release-branch: false
    tracks-release-branches: true
    source-branches: ['release']
    is-source-branch-for: ['feature','bug','release']
  bug:
    regex: bug(s)?[/-] 
    tag: 'bug.{BranchName}'
    increment: None
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    is-release-branch: false
    tracks-release-branches: true
    source-branches: ['release','hotfix','feature']
    is-source-branch-for: ['feature','bug','release']
  develop:
    regex: develop
    tag: ''
    increment: None
    prevent-increment-of-merged-branch-version: true
    tracks-release-branches: false
    track-merge-target: false
    is-release-branch: false
    is-source-branch-for: ['develop']
    source-branches: ['develop']
