commit-message-incrementing: Disabled
branches:
  master:
    regex: master
    mode: Mainline
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    is-release-branch: false
    is-source-branch-for: ['hotfix','release']
  hotfix:
    regex: hotfix(es)?[/-]
    mode: ContinuousDelivery
    tag: 'hotfix.{BranchName}'
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    is-release-branch: false
    source-branches: ['master']
  release:
    regex: releases?[/-]
    mode: ContinuousDelivery
    tag: useBranchName
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    is-release-branch: true
    is-source-branch-for: ['feature','bug']
  feature:
    regex: features?[/-]
    mode: ContinuousDelivery
    tag: 'feature.{BranchName}'
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    is-release-branch: false
    tracks-release-branches: true
    source-branches: ['release']
  bug:
    regex: bug(s)?[/-] 
    mode: ContinuousDelivery
    tag: 'bug.{BranchName}'
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    is-release-branch: false
    source-branches: ['release']
