#assembly-informational-format:'env:Build.BuildNumber ? Builded with {env:Build.DefinitionName}_{env:Build.BuildNumber} : {informational}'
commit-message-incrementing: Disabled
assembly-versioning-format: '{Major}.{Minor}.0.0'
branches:
  master:
    regex: master
    mode: ContinuousDelivery
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    is-release-branch: false
  hotfix:
    regex: hotfix(es)?[/-]
    mode: ContinuousDelivery
    tag: 'hotfix.{BranchName}'
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    is-release-branch: false
    source-branches : ['master']
  release:
    regex: releases?[/-]
    mode: ContinuousDelivery
    tag: rc
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    is-release-branch: true
    source-branches : ['master']
  feature:
    regex: features?[/-]
    mode: ContinuousDelivery
    tag: 'feature.{BranchName}'
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    is-release-branch: false
    source-branches : ['release']
  bug:
    regex: bug(s)?[/-] 
    mode: ContinuousDelivery
    tag: 'bug.{BranchName}'
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    is-release-branch: false
    source-branches : ['release']
